                    Module 4: Data Structure Assignment



Create a list named ‘myList’ that is having the following elements: 10,20,30,’apple’, True, 8.10.

a. Now in the ‘myList’, append these values: 30,40

b. After that reverse the elements of the ‘myList’ and store that in ‘reversedList’

In [13]:
mylist= [10,20,30, "apple", True, 8.10]

mylist.append([30, 40])

mylist.reverse()
mylist

[[30, 40], 8.1, True, 'apple', 30, 20, 10]

2. Create a dictonary with key values as 1,2,3 and the values as ‘data’,’information’, and ‘text’.

a. After that eliminate the ‘text’ value form the dictonary.

b. Add ‘features’ in the dictonary.

c. Fetch the ‘data’ element from the dictonary and display it in the output.

In [5]:
k= (1,2,3)
V=('data', 'information', 'text')
d= dict(zip(k,V))
d




{1: 'data', 2: 'information', 3: 'text'}

In [6]:
#a. After that eliminate the ‘text’ value form the dictonary.

d.pop(3)
d

{1: 'data', 2: 'information'}

In [7]:
#b. Add ‘features’ in the dictonary.

d[3]='features'
d

{1: 'data', 2: 'information', 3: 'features'}

In [8]:
#c. Fetch the ‘data’ element from the dictonary and display it in the output.

d[1]

'data'

3. Create a tuple and add these elements 1,2,3,apple,mango in ‘my_tuple

In [13]:
my_tuple=(1,2,3,'apple','mango')

4. Create another tuple named numeric_tuple consisting of only integer values 10,20,30,40,50

a. Find the minimum value from the numeric_tuple.

b. Concatenate my_tuple with numeric_tuple and store the result in r1.

c. Duplicate the tuple named my_tuple 2 times and store that in ‘newdupli’.

In [14]:
numeric_tuple= (10,20,30,40,50)
numeric_tuple

(10, 20, 30, 40, 50)

In [15]:
#a. Find the minimum value from the numeric_tuple.

min(numeric_tuple)

10

In [16]:
#b. Concatenate my_tuple with numeric_tuple and store the result in r1.

r1= my_tuple+numeric_tuple
r1

(1, 2, 3, 'apple', 'mango', 10, 20, 30, 40, 50)

In [17]:
#c. Duplicate the tuple named my_tuple 2 times and store that in ‘newdupli’.

newdupli= ((my_tuple)*2)
newdupli

(1, 2, 3, 'apple', 'mango', 1, 2, 3, 'apple', 'mango')

5. Create 2 sets with name set1 and set2, where set1 contains{1,2,3,4,5} and set2 to 
contains{2,3,7,6,1}

a. Perform the below operation:

    a. set1 union set2

    b. set1 intersection set2 


    c. set1 difference set2

In [18]:
set1= {1,2,3,4,5}
set2= {2,3,7,6,1}

In [19]:
#a. set1 union set2

set1.union(set2)

{1, 2, 3, 4, 5, 6, 7}

In [20]:
#b. set1 intersection set2 

set1.intersection(set2)

{1, 2, 3}

In [21]:
#c. set1 difference set2

set1.difference(set2)

{4, 5}

                    Module 4: Numpy Assignment

1. Create a 3x3 matrix array with values ranging from 2 to 10.

In [25]:
import numpy as np

np.arange(2,11).reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

2. Create a numpy array having user input values and convert the integer type to the float type 
of the elements of the array. For instance:

    Original array

    [1, 2, 3, 4]

    Array converted to a float type:

    [ 1. 2. 3. 4.]


In [29]:
a= []

n=int(input('entry the size of the array: '))

for i in range(0,n):
    a.append(int(input('element: ')))
    
arr=np.array(a)
    
arr.dtype    

entry the size of the array: 3
element: 10
element: 20
element: 30


dtype('int32')

In [30]:
arr.astype(float)

array([10., 20., 30.])

3. Write a Numpy program to append values to the end of an array. For instance:

Original array:
[10, 20, 30]

After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]


In [38]:
array1= np.array([1, 8, 3, 3, 5])

array2= np.append(array1, [20,30,40])

array2

array([ 1,  8,  3,  3,  5, 20, 30, 40])

4. Create two numpy arrays and add the elements of both the arrays and store the result in 
sumArray.

In [39]:
array1=np.array([1,2,3])
array2=np.array([2,3,4])

array3= array1+array2
array3

array([3, 5, 7])

5. Create a 3*3 array having values from 10-90(interval of 10) and store that in array1. Perform 
the following tasks:

a. Extract the 1st row from the array.

b. Extract the last element from the array

In [57]:
array1= np.arange(10,91,10)
array1=array1.reshape(3,3)
array1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [53]:
#a. Extract the 1st row from the array.

array1[0:1]

array([[10, 20, 30]])

In [68]:
#b. Extract the last element from the array

array1[-1][-1]

90

                        Module 4: Numpy Assignment

1. Create a function that takes dimensions as tuples e.g.(3, 3) and a numeric value and returns a 
Numpy array of the given dimension filled with the given value e.g.: solve((3, 3), 5) will return 

[
 [5, 5, 5],
 [5, 5, 5],
 [5, 5, 5]
]


In [74]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

2. Create a method that takes n Numpy arrays of same dimensions sums them and return the 
answer.

In [72]:
def arr_sum(*args):
    arr3=np.add(*args)
    return arr3

arr5= np.array([1,2,3,4,5])
arr6= np.array([2,3,7,6,1])
arr_sum(arr5, arr6)

array([ 3,  5, 10, 10,  6])

3. Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two 
numbers N and M. The method should return the top-left N X M sub matrix e.g:
 
 [
 [1, 2, 3],
 [4, 5, 6],
 [7, 8, 9],
 ]

top_left_sub_matrix (matrix, 2, 2) -> should return:
 
 [
 [1, 2]
 [4, 5]
 ]


In [77]:
def arr_slice(array,n,m):
    arr3=array[0:n,0:m]
    return arr3



4. Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two 
numbers N and M The method should return the bottom-right N X M sub matrix e.g.:
 
 [
 [1, 2, 3],
 [4, 5, 6],
 [7, 8, 9],
 ]

sub_matrix(matrix, 1, 1) -> should return : (Keep in mind these arrays are zero indexed)
 
 [
 [5, 6]
 [8, 9]
 ]


In [78]:
def arr_slice(array,n,m):
    arr3=array[1: ,1:]
    return arr3

5. Given a 1 D Numpy Array. Write a function that accepts this array as parameters. The method 
should return a dictionary with 'mean' and 'std_dev' as key and array's mean and array's 
standard deviation as values:
 
 [1, 1, 1]
solution(arr) -> should return :
 {'mean': 1.0, 'std_dev': 0.0}

In [79]:
def fun(a):
    mean=a.mean()
    std_dev=a.std()
    return {'mean':mean, 'std_dev':std_dev}