In [4]:
#hands on 1 - data processing
# Step 4: Import the required packages and create a list
# Step 5: Print the type of the variable

import numpy as np
import pandas as pd

num_list = [1,2,3,4,5]
type(num_list)

list

In [5]:
# Step 6: Create and reshape a NumPy array

arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [6]:
arr = arr.reshape((2,3))
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# Step 7: Create a NumPy array filled with zeroes and a NumPy array with values
# from 1 to 9 and reshape it

np.zeros((1,3))

array([[0., 0., 0.]])

In [8]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# Step 8: Create a DataFrame using a 1d list and a 2d list

pd.DataFrame([1,2,3,4])

0
0  1
1  2
2  3
3  4

In [10]:
pd.DataFrame([[1,2,3],['a','b','c']])

0  1  2
0  1  2  3
1  a  b  c

In [11]:
# Step 9: Create a DataFrame using a dictionary

pd.DataFrame({
    'id':[1,2,3],
    'Name':['a','b','c']
}).set_index('id')

Name
id     
1     a
2     b
3     c